# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_least_sq_via_qr_cpp_eig <- function(X, y) {
    .Call(`_hiperglm_solve_least_sq_via_qr_cpp_eig`, X, y)
}

row_subset_matvec_via_transpose <- function(tA, v, row_index) {
    .Call(`_hiperglm_row_subset_matvec_via_transpose`, tA, v, row_index)
}

col_subset_matvec <- function(tA, v, col_index) {
    .Call(`_hiperglm_col_subset_matvec`, tA, v, col_index)
}

